# Generated by Django 5.2.6 on 2025-09-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_booking_department_remove_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='doctors',
            new_name='Doctor',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dep_discription',
            new_name='dep_description',
        ),
    ]
